version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # prisma:
  #   image: node:18
  #   container_name: prisma
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - postgres
  #   command: >
  #     sh -c "npm install && npx prisma migrate dev"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/mydatabase"

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/mydatabase"

volumes:
  postgres_data:
